### ISSUE TITLE
Is it possible to update this repo to Sensu 0.25.x?

### ISSUE THREAD

**Issue by samjarrett** [anroots/sensu-stack#5]

**Comment by anroots** [comment]
I'll try to look into it in the next couple of days (currently ill). To expedite things, you're welcome to send a pull request. :)

**Comment by anroots** [comment]
I've pushed `0.3.0` tags for all the components to the Docker registry and updated my own instance of Sensu to those tags - it seems to work without problems, at Sensu version `0.25.7`.

Please check it out and report any problems.
